### PR TITLE
Feat: Change Hex and filter results 

### PR DESCRIPTION
**Pull request by trantrongkim98**
- [x] Remove Data type at steps axtj and only take type is "STRN"
- [x] Change hex to "63 65 72 74 5F 63 6F 75 6E 74 00"

### CODE REVIEW

**Comment by TheVisual** [comment]
@Eltion 🙏 merge please for us. its indeed working

**Comment by TheVisual** [comment]
@trantrongkim98 can you confirm if broken again?

**Comment by Eltion** [comment]
@trantrongkim98 thanks a lot for this PR, it seems like in the new versions tiktok has changed the ssl pinning method a bit so I will close this for now.

**Comment by Sasa2023** [comment]
@trantrongkim98 This fix doesn't work for version 36.5.4 I can't patch the libsscronet.so

**Pull request closed without merging**
