### PR TITLE
Disable forced login

### PR DESCRIPTION
**Pull request by hackercxj**
Tiktok will force user to login if device is abnormal. Use this to disable forced login.

### CODE REVIEW

**Review by baibhavanand — APPROVED** [review]

**Comment by Eltion** [comment]
@hackercxj  thanks for the pull request, could you maybe explain how tiktok forces users to login? Could you sent some screenshots.

**Comment by baibhavanand** [comment]
I can confirm, this indeed was an issue and this PR fixes it.

**Comment by hackercxj** [comment]
@Eltion @baibhavanand  Of course. I remember the forced login logic in jadx is as follows:
image
image

Actually, a better way is to carefully examine what the enableForcedLogin function specifically detects. Here, I took a shortcut and directly set "is_skippable_dialog" to true, which also works.

The login page cannot be closed：
image

Setting "is_skippable_dialog" to true allows it to be closed：
image

**Comment by idammi** [comment]
@hackercxj @Eltion Can you upload the decompiled TikTok APK to a private repo and add me please

**Comment by hackercxj** [comment]
@baibhavanand Try decompiling it yourself, maybe you can ask ChatGPT for help.

**Comment by idammi** [comment]
I already did. Used ChatGPT too. Thanks

**Comment by abdullahsaeed98** [comment]
> is_skippable_dialog

I want to achieve the same in TIktok iOS decrpyed ipa but I dont know how I can find that specfic funtion to hook it with frida. 
can you help me with that?

**Pull request closed without merging**
